---
title: "Lista 2a"
subtitle: "Análise de Regressao Linear"
author: "Davi Wentrick"
header_left: "Runninghead"
header_right: "Author"
date: \today
fontsize: 11pt
german: false # default is English"
output: 
  UHHformats::pdf_simple:
    font: "Helvetica" # alternative: "TheSansUHH"  
---

```{r setup, include = FALSE}
# settings --> keep this chunk as it is!
knitr::opts_chunk$set(echo = FALSE, message = FALSE, 
  warning = FALSE, error = FALSE, cache = TRUE,
  fig.path='figs/', cache.path = 'cache/')
```

```{r load-packages, include = FALSE}
# packages
library(knitr)
library(kableExtra)
library(xtable)
library(tidyverse)
```

```{r generate-package-refs, include=FALSE}
# Create a bib database for R packages used above
# NOTE: RUN THIS CODE CHUNK MANUALLY TO CREATE FILE BEFORE KNITTING
knitr::write_bib(
  x = c(.packages(), 'bookdown', 'rmarkdown', 'UHHformats',
    # Add here now all packages that are loaded above:
    'knitr', 'kableExtra', 'xtable', 'tidyverse'),
  file = 'bib/packages.bib'
)
```

<!-- This is how you can define comments in an .Rmd file (outside the R code snippets) -->


# Considere a função resposta: $E(Y) = 25+3X_1+4X_2+1,5X_1X_2$



##  Faça o gráfico de $E(Y) \times X_1$ quando $X_2 = 3$ e $X_2 = 6$ .
##  Os efeitos de $X_1$ e $X_2$ são aditivos? Como você identificou isto no gráfico obtido no item a.


# Estabeleça a matriz $X$ e os vetores $Y$ $\beta$ e para os seguintes modelos (assuma que $i=1,2,3,4$).

## $Y_i = \beta_0+\beta_1X_{i1}+\beta_2X_{i1}X_{i2}+\epsolon_i$
##
